### ISSUE TITLE
Settings menu only opens on first click after reload 

### ISSUE THREAD

**Issue by morremeyer** [michenriksen/gokiburi#7]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The settings button is only clickable once when the site is loaded.

When the menu is closed after the button has been clicked, the button does not do anything anymore.

### Expected Behavior

Settings button is clickable unlimited number of times.

### Steps To Reproduce

1. Use the environment described below
2. Start gokiburi
3. Click the settings button -> Menu opens
4. Close the menu
5. Click the button again -> Nothing happens

### Environment

```markdown
- OS: macOS 13.3.1
- Architecture: arm
- Gokiburi: 0.1.3
- Browser: Firefox 113.0.1
```

### Anything else?

I checked the Browser console, there were no logs for this. If I can debug this any further, let me know 😊

**Comment by michenriksen** [comment]
Hi there, thanks for reporting! This looks like an issue similar to #2 which should be a pretty straight-forward fix.
